//! Menu bar presence (task 4.1): tray icon, popover shell, activation
//! policy, and the tray menu.
//!
//! Window model:
//! - `popover`: a small undecorated always-on-top window anchored under the
//!   tray icon. Left-clicking the tray toggles it; losing focus (click-away)
//!   hides it. Both windows are defined in `tauri.conf.json` and live for
//!   the whole app lifetime; show/hide only, never destroyed.
//! - `main`: the desktop app window, hidden at startup. Opening it (tray
//!   menu) flips the macOS activation policy to `Regular` so a Dock icon
//!   appears; closing it hides the window and flips back to `Accessory`
//!   so the Dock icon disappears while the app stays resident.
//!
//! The "Pause capture" check item drives `capture::apply_paused` (task
//! 4.4): the receiver discards (200 + drop) while paused, the tray shows a
//! "Paused" title badge next to the icon, and the persisted state restores
//! the menu check + badge on the next launch.

use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use tauri::menu::{CheckMenuItem, Menu, MenuEvent, MenuItem, PredefinedMenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{AppHandle, Manager, Runtime, Window, WindowEvent};
use tauri_plugin_positioner::{Position, WindowExt};

use crate::capture::{self, CaptureState};

pub const MAIN_WINDOW: &str = "main";
pub const POPOVER_WINDOW: &str = "popover";

/// Tray icon id, used to look the icon up for the paused title badge.
pub const TRAY_ID: &str = "main-tray";

/// Menu-bar badge shown next to the tray icon while capture is paused.
const PAUSED_BADGE: &str = "Paused";

const MENU_OPEN_APP: &str = "open-app";
const MENU_PAUSE: &str = "pause";
const MENU_QUIT: &str = "quit";

/// Click-away dismissal hides the popover from the focus-loss handler. When
/// the click that stole focus was on the tray icon itself, a `Click` tray
/// event arrives right after the hide; without suppression that click would
/// instantly re-show the window, making the tray icon impossible to use as
/// a "close" toggle. Tray clicks landing within this window of an auto-hide
/// are treated as "the popover was open; leave it closed".
const REOPEN_SUPPRESS_WINDOW: Duration = Duration::from_millis(300);

/// Shared tray state: the popover auto-hide timestamp used for tray-click
/// toggle suppression. (The capture-pause flag lives in
/// [`crate::capture::CaptureState`] since task 4.4.)
#[derive(Clone, Default)]
pub struct TrayState {
    popover_hidden_at: Arc<Mutex<Option<Instant>>>,
}

impl TrayState {
    fn note_popover_hidden(&self) {
        *self.popover_hidden_at.lock().expect("tray state poisoned") = Some(Instant::now());
    }

    fn suppress_reopen(&self) -> bool {
        self.suppress_reopen_at(Instant::now())
    }

    fn suppress_reopen_at(&self, now: Instant) -> bool {
        self.popover_hidden_at
            .lock()
            .expect("tray state poisoned")
            .is_some_and(|hidden_at| {
                now.saturating_duration_since(hidden_at) < REOPEN_SUPPRESS_WINDOW
            })
    }
}

/// Handle to the "Pause capture" check item, managed so pause changes made
/// outside the menu (popover resume button) can sync the check state.
pub struct PauseMenuHandle<R: Runtime>(CheckMenuItem<R>);

/// Builds the tray icon + menu and switches the app to menu-bar-only mode.
/// Called once from the app `setup` hook, after `CaptureState` is managed:
/// the persisted pause state seeds the menu check + paused badge.
pub fn setup(app: &mut tauri::App) -> tauri::Result<()> {
    let state = TrayState::default();
    app.manage(state);

    // Menu-bar-only at startup: no Dock icon until the desktop window is
    // opened (see handle_menu_event / handle_window_event).
    #[cfg(target_os = "macos")]
    app.set_activation_policy(tauri::ActivationPolicy::Accessory);

    let paused = app.state::<CaptureState>().paused();

    let open_app = MenuItem::with_id(app, MENU_OPEN_APP, "Open Farthing", true, None::<&str>)?;
    let pause =
        CheckMenuItem::with_id(app, MENU_PAUSE, "Pause capture", true, paused, None::<&str>)?;
    let quit = MenuItem::with_id(app, MENU_QUIT, "Quit", true, None::<&str>)?;
    let menu = Menu::with_items(
        app,
        &[
            &open_app,
            &PredefinedMenuItem::separator(app)?,
            &pause,
            &PredefinedMenuItem::separator(app)?,
            &quit,
        ],
    )?;

    // Dedicated menu bar glyph (task 6.1): black+alpha template image, so
    // macOS recolors it for dark/light menu bars (`icon_as_template` below).
    // Regenerated by scripts/generate-icons.py.
    let icon = tauri::image::Image::from_bytes(include_bytes!("../icons/tray-icon.png"))
        .expect("bundled tray template icon is a valid PNG");

    // Managed so capture::apply_paused can sync the check state when the
    // pause changes from outside the menu (popover resume button).
    app.manage(PauseMenuHandle(pause.clone()));

    let tray = TrayIconBuilder::with_id(TRAY_ID)
        .icon(icon)
        // Template image: macOS renders it as a monochrome glyph that adapts
        // to the menu bar appearance (dark/light).
        .icon_as_template(true)
        .tooltip("Farthing")
        .menu(&menu)
        // Left click toggles the popover; the menu stays on right click.
        .show_menu_on_left_click(false)
        .on_menu_event(move |app, event| handle_menu_event(app, &event, &pause))
        .on_tray_icon_event(|tray, event| {
            // Feed the positioner so Position::TrayBottomCenter knows where
            // the icon is (multi-monitor / scale-factor aware).
            tauri_plugin_positioner::on_tray_event(tray.app_handle(), &event);
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            } = event
            {
                toggle_popover(tray.app_handle());
            }
        })
        .build(app.handle())?;

    // Restore the paused badge for a launch into a persisted pause.
    if paused {
        let _ = tray.set_title(Some(PAUSED_BADGE));
    }

    Ok(())
}

fn handle_menu_event<R: Runtime>(app: &AppHandle<R>, event: &MenuEvent, pause: &CheckMenuItem<R>) {
    match event.id().as_ref() {
        MENU_OPEN_APP => show_main_window(app),
        MENU_PAUSE => {
            // The check item toggles natively; persist + fan out the new
            // state (receiver flag, badge, frontend event). If persisting
            // fails, resync the UI to the unchanged real state.
            let checked = pause.is_checked().unwrap_or(false);
            if let Err(err) = capture::apply_paused(app, checked) {
                eprintln!("tray: pause toggle failed: {err}");
                sync_paused_ui(app, app.state::<CaptureState>().paused());
            }
        }
        MENU_QUIT => app.exit(0),
        _ => {}
    }
}

/// Bring the tray UI in line with `paused`: menu check state + the menu-bar
/// "Paused" title badge. Tolerates a missing tray/menu (tests, startup
/// ordering) — state is owned by `CaptureState`, this is presentation only.
pub fn sync_paused_ui<R: Runtime>(app: &AppHandle<R>, paused: bool) {
    if let Some(handle) = app.try_state::<PauseMenuHandle<R>>() {
        let _ = handle.0.set_checked(paused);
    }
    if let Some(tray) = app.tray_by_id(TRAY_ID) {
        // Clear with Some("") — set_title(None) leaves the previous title in
        // place on macOS (live-verified).
        let _ = tray.set_title(Some(if paused { PAUSED_BADGE } else { "" }));
    }
}

/// Frontend command (task 5.1): the popover's "Open app" button opens the
/// desktop window. Commands run off the main thread, and activation-policy /
/// window mutations must happen on it (same constraint as the tray-menu
/// mutations found in task 4.4), so the actual work is dispatched.
#[tauri::command]
pub fn open_main_window<R: Runtime>(app: AppHandle<R>) {
    // The popover would hide on focus loss anyway once the main window takes
    // focus; hiding it here makes the handoff immediate.
    if let Some(popover) = app.get_webview_window(POPOVER_WINDOW) {
        let _ = popover.hide();
    }
    let handle = app.clone();
    let _ = app.run_on_main_thread(move || show_main_window(&handle));
}

/// Opens (or re-focuses) the desktop window and brings back the Dock icon.
fn show_main_window<R: Runtime>(app: &AppHandle<R>) {
    let Some(window) = app.get_webview_window(MAIN_WINDOW) else {
        return;
    };
    // Policy first so the app can become a regular foreground app before
    // the window asks for focus.
    #[cfg(target_os = "macos")]
    let _ = app.set_activation_policy(tauri::ActivationPolicy::Regular);
    let _ = window.show();
    let _ = window.set_focus();
}

/// Left tray click: hide the popover if it is showing, otherwise anchor it
/// under the tray icon and show it.
fn toggle_popover<R: Runtime>(app: &AppHandle<R>) {
    let Some(window) = app.get_webview_window(POPOVER_WINDOW) else {
        return;
    };
    if window.is_visible().unwrap_or(false) {
        let _ = window.hide();
        return;
    }
    if app.state::<TrayState>().suppress_reopen() {
        // The click-away handler hid the popover for this same click on the
        // tray icon: the user meant "close".
        return;
    }
    let _ = window.move_window(Position::TrayBottomCenter);
    let _ = window.show();
    let _ = window.set_focus();
}

/// Registered via `Builder::on_window_event` for every window.
pub fn handle_window_event<R: Runtime>(window: &Window<R>, event: &WindowEvent) {
    match (window.label(), event) {
        // Click-away dismissal for the popover.
        (POPOVER_WINDOW, WindowEvent::Focused(false)) if window.is_visible().unwrap_or(false) => {
            let _ = window.hide();
            window
                .app_handle()
                .state::<TrayState>()
                .note_popover_hidden();
        }
        // Closing the desktop window hides it (the app keeps running in the
        // menu bar) and drops the Dock icon again.
        (MAIN_WINDOW, WindowEvent::CloseRequested { api, .. }) => {
            api.prevent_close();
            let _ = window.hide();
            #[cfg(target_os = "macos")]
            let _ = window
                .app_handle()
                .set_activation_policy(tauri::ActivationPolicy::Accessory);
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Presentation-only sync: with no tray icon and no managed menu handle
    /// (mock runtime), syncing must be a silent no-op, not a panic.
    #[test]
    fn sync_paused_ui_tolerates_missing_tray_and_menu() {
        let app = tauri::test::mock_builder()
            .build(tauri::test::mock_context(tauri::test::noop_assets()))
            .expect("mock app");
        sync_paused_ui(app.handle(), true);
        sync_paused_ui(app.handle(), false);
    }

    /// The command must tolerate missing windows (mock runtime has none):
    /// it dispatches to the main thread and silently no-ops.
    #[test]
    fn open_main_window_tolerates_missing_windows() {
        let app = tauri::test::mock_builder()
            .build(tauri::test::mock_context(tauri::test::noop_assets()))
            .expect("mock app");
        open_main_window(app.handle().clone());
    }

    /// The tray glyph is loaded with `expect` during setup; pin that the
    /// embedded PNG (scripts/generate-icons.py output) actually decodes and
    /// is the expected small square template size.
    #[test]
    fn embedded_tray_template_icon_decodes() {
        let icon = tauri::image::Image::from_bytes(include_bytes!("../icons/tray-icon.png"))
            .expect("tray-icon.png decodes");
        assert_eq!((icon.width(), icon.height()), (32, 32));
    }

    #[test]
    fn reopen_not_suppressed_without_prior_hide() {
        let state = TrayState::default();
        assert!(!state.suppress_reopen());
    }

    #[test]
    fn reopen_suppressed_immediately_after_auto_hide() {
        let state = TrayState::default();
        state.note_popover_hidden();
        assert!(state.suppress_reopen());
    }

    #[test]
    fn reopen_allowed_after_suppress_window_elapses() {
        let state = TrayState::default();
        state.note_popover_hidden();
        let later = Instant::now() + REOPEN_SUPPRESS_WINDOW + Duration::from_millis(1);
        assert!(!state.suppress_reopen_at(later));
    }
}
